### ISSUE TITLE
Ошибка сравнения билета, с уже добавленным(ими) билетом(ами)

### ISSUE THREAD

**Issue by UrilKxx** [EpicDima/TicketHolder#1]
При добавлении и последующем сравнении билета типа:

>\# 0 \# 0
>\# \# 0 0
>\# 0 \# 0

Билет не находится, а  выскакивает предложение добавление его в список(базу) в качестве нового, хотя билет уже был добавлен

**Comment by UrilKxx** [comment]
А также билет типа:
>0 # 0 #
>0 # # 0
>0 # 0 #

**Comment by UrilKxx** [comment]
А также билеты типа:
>0 \# \# 0
>0 0 0 0
>\# \# \# 0
-------------
>0 \# 0 \#
>0 \# 0 \#
>0 \# 0 \#
-------------
>\# 0 \# 0 
>\# 0 \# 0 
>\# 0 \# 0

**Comment by UrilKxx** [comment]
Ошибка в методе сравнения.
Ошибка исправлена, добавлены тесты

**Comment by EpicDima** [comment]
> 
> 
> Ошибка в методе сравнения.
> Ошибка исправлена, добавлены тесты

Пока Pull Request не принят и не слит с веткой ошибка не может быть исправлена
